name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 3.109.198.252 >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@3.109.198.252 << EOF
          cd /var/www/html/sign-assign/sign-assign-web/
          sudo chown -R ubuntu:ubuntu /var/www/html/sign-assign/sign-assign-web/
          git pull origin master
          sudo chown -R www-data:www-data /var/www/html/sign-assign/sign-assign-web/
          # Optional: restart your app if needed, like:
          # pm2 restart all
        EOF
